version: '3'

networks: 
  server: 

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80" 
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks: 
      - server

  mysql: 
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: client_name
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes: 
      - ./mysql:/var/lib/mysql
    networks: 
      - server

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports: 
      - "9000:9000"
    networks: 
      - server
  
  composer:
    image: composer:latest
    container_name: composer
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks: 
      - server

  npm: 
    image: node:latest
    container_name: npm
    volumes: 
      - ./src/build_files:/var/www/html/build_files
    working_dir: /var/www/html/build_files
    entrypoint: ['npm']
    networks: 
      - server